build:
  frontend:
    image: node:6.9-slim
    commands:
      - npm run test
notify:
  email:
    from: drone@birkhoff.me
    host: smtp.gmail.com
    username: $$GMAIL_USERNAME
    password: $$GMAIL_PASSWORD
    recipients:
      - admin@birkhoff.me
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    template: >
      https://git.io/vgvPz